version: '3.4'
services:
  portal_db:
    image: mysql:8.0
    container_name: portal-mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'portal_db'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      TZ: UTC
    ports:
      - 3306:3306
  portal-client:
    build:
      context: ./portal-client
      args:
        PORT: "5001"
        NODE_ENV: "${NODE_ENV}"
        REACT_APP_BASE_API_URL: "${BASE_API_URL}"
    image: portal-client
    container_name: portal-client
    restart: always
    depends_on: 
      - portal-server
    ports:
      - "5001:5001"
    command: sh -c './client-start.sh'
  portal-server:
    build:
      context: ./portal-server
      args:
        PORT: 5000
        NODE_ENV: "${NODE_ENV}"
    image: portal-server
    container_name: portal-server
    restart: always
    ports:
      - "5000:5000"
    command: sh -c './wait-for-it portal_db:3306 -- ./server-start.sh'
    depends_on: 
      - portal_db
    links: 
      - portal_db
